Use Org-Wide Secrets and PDNS Account for Image Push
PowerDNS/weakforced pull request #430
Opened 2024-06-26 09:30 UTC by neilcook

2024-07-01 11:03 UTC, Habbie requested changes

2024-07-01 11:03 UTC, Habbie commented on .github/workflows/docker.yml
> +          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER_NAME }}
```suggestion
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
```

2024-07-02 07:43 UTC, neilcook commented on .github/workflows/docker-minimal.yml
> +          username: ${{ secrets.DOCKERHUB_USER_NAME }}
That's weird I thought I'd just cut and pasted. Thanks for the catch!

2024-07-04 12:26 UTC, Habbie approved these changes
LGTM, assuming you tested it :)

2024-07-08 11:10 UTC, merged